// Sedulo Digital — Tailwind Config Extension
// Generated by Sedulo Digital Brand Playbook v1.0

module.exports = {
  theme: {
    extend: {
      colors: {
        'sd-black': '#0A0A0A',
        'sd-ink': '#141414',
        'sd-graphite': '#1F1F1F',
        'sd-slate': '#3A3A3A',
        'sd-ash': '#6B6B6B',
        'sd-smoke': '#A3A3A3',
        'sd-fog': '#D6D6D6',
        'sd-cloud': '#EDEDED',
        'sd-paper': '#F6F6F4',
        'sd-white': '#FFFFFF',
        'sd-accent': '#C4A882',
        'sd-accent-deep': '#8C7355',
        'sd-accent-soft': '#F0E8DC',
        'sd-success': '#2E7D57',
        'sd-warn': '#C97A1F',
        'sd-danger': '#B33A2F',
        'sd-info': '#2E5B8A',
      },
      fontFamily: {
        display: ['Poppins', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-xl': ['96px', { lineHeight: '1.02', letterSpacing: '-0.02em' }],
        'display-l': ['72px', { lineHeight: '1.02', letterSpacing: '-0.02em' }],
        'display': ['56px', { lineHeight: '1.02', letterSpacing: '-0.02em' }],
        'h1': ['44px', { lineHeight: '1.1', letterSpacing: '-0.01em' }],
        'h2': ['32px', { lineHeight: '1.15' }],
        'h3': ['24px', { lineHeight: '1.25' }],
        'h4': ['20px', { lineHeight: '1.3' }],
        'lead': ['20px', { lineHeight: '1.55' }],
        'body': ['17px', { lineHeight: '1.55' }],
        'sm': ['15px', { lineHeight: '1.5' }],
        'xs': ['13px', { lineHeight: '1.5' }],
        'eyebrow': ['12px', { lineHeight: '1.4', letterSpacing: '0.14em' }],
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '6': '24px',
        '8': '32px',
        '12': '48px',
        '16': '64px',
        '24': '96px',
        '32': '128px',
      },
      borderRadius: {
        'none': '0px',
        'xs': '2px',
        'sm': '4px',
        'md': '6px',
        'lg': '12px',
        'pill': '999px',
      },
      maxWidth: {
        'page': '1280px',
        'prose': '68ch',
      },
      transitionTimingFunction: {
        'sd-out': 'cubic-bezier(0.2, 0.7, 0.2, 1)',
      },
      transitionDuration: {
        'fast': '120ms',
        'base': '200ms',
        'slow': '360ms',
      },
    },
  },
}
